Install necessary peer dependencies
JonasKruckenberg/imagetools pull request #296
Opened 2021-12-21 19:04 UTC by benmccann

- **Quick Checklist**

* [X] I have read [the contributing guidelines](../CONTRIBUTING.md)
* [ ] I have written new tests, as applicable (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] I have added a changeset, if applicable

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Cleanup

- **What is the new behavior (if this is a feature change)?**

None

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this
  PR?)

No

- **Other information**:

`rollup-plugin-typescript2` has tons of required peerDependencies that aren't installed. Switch to `@rollup/plugin-typescript` instead since it has fewer required peerDependencies and then install them (i.e. `tslib`). `rollup-plugin-typescript2` was originally better than `@rollup/plugin-typescript`, but the latter has improved quite a bit and now is the better library and far better tested (`rollup-plugin-typescript2` has no tests whatsoever)

2021-12-21 19:37 UTC, JonasKruckenberg commented
Does `@eollup/plugin-typescript` generate typings now? That was the only reason for `rollup-plugin-typescript2`.

2021-12-21 20:01 UTC, benmccann commented
Yes, I believe it should: https://github.com/rollup/plugins/issues/61

I'm not sure if there might be some additional configuration needed for that to happen or if it's already happening with this PR

2021-12-21 20:40 UTC, benmccann commented
I've pushed a change to make it so that types are generated with this PR

2021-12-22 15:14 UTC, JonasKruckenberg requested changes

2021-12-22 15:14 UTC, JonasKruckenberg commented on packages/core/package.json
> +  "types": "dist/types.d.ts",
```suggestion
  "types": "dist/index.d.ts",
```

`index.d.ts` exports all type declarations (including functions and objects), `typed.d.ts` is just exporting common interface declarations and type aliases.

2021-12-22 15:14 UTC, JonasKruckenberg commented on packages/rollup/package.json
> +  "types": "dist/types.d.ts",
```suggestion
  "types": "dist/index.d.ts",
```

2021-12-22 15:14 UTC, JonasKruckenberg commented on packages/vite/package.json
> +  "types": "dist/types.d.ts",
```suggestion
  "types": "dist/index.d.ts",
```

2021-12-24 07:05 UTC, benmccann commented
this is strange. I can't reproduce any failure locally eventhough the CI keeps failing

2021-12-24 09:44 UTC, JonasKruckenberg commented
We love jest 🙃

2021-12-24 18:12 UTC, benmccann commented
Maybe I'll finally have a reason to try out the new https://vitest.dev/

2022-01-28 23:59 UTC, JonasKruckenberg commented
I ended up implementing this myself, to fix that annoying jest issue, but thanks for your PR anyway!
repo uses pnpm now 😉

2022-01-28 23:59 UTC, closed without merging

2022-01-29 00:22 UTC, benmccann commented
that's great! thank you so much!